# Generated by Django 2.1.9 on 2019-06-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bamboo',
        ),
    ]
